version: '3.8'
services:
  app:    
    build:
      context: .
      dockerfile: Dockerfile        
    ports:
      - 3000:3000     
    environment:
      DB_DIALECT: postgres
      DB_HOST: node_db
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: population-analyst-api-db
    depends_on:
      - node_db 
    volumes:
      - ./:/src
      
  node_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: population-analyst-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - node_db_data:/var/lib/postgresql/data
volumes:
  node_db_data: {}
